### PR TITLE
fix: support lit shared subpaths

### LINKED ISSUE #606: [Bug]: Cannot share lit properly
### Describe the bug

Since upgrading from a much earlier version (`1.8.0`) to more recent ones (`1.12.3`, `1.13.5`, also reproducible on latest `1.14.2`) along side with core MF deps, we are having problems sharing `lit` dependencies properly. 

The problem arises when using [directives](https://lit.dev/docs/templates/directives/). For the better or worse, they are provided by `lit-html` but lit exposes them as re-exports through the main `lit` package, like [here](https://github.com/lit/lit/blob/main/packages/lit/src/directives/class-map.ts). (plus some more "interesting" [shenanigans](https://github.com/lit/lit/blob/main/packages/lit/src/index.ts#L7-L11)). This might play a reason why the build is bundling them instead of sharing, as shown in the following?

I saw that you have a [lit example](https://github.com/gioboa/module-federation-vite-examples/tree/main/lit) already in place for like e2e validation, that's why I built on top of that for my [reproduction](https://github.com/gioboa/module-federation-vite-examples/pull/2). In the [first commit](https://github.com/gioboa/module-federation-vite-examples/pull/2/changes/a8487e2aad3ba2a9760a1d7fac81bdbfb2fc2140), I added some (rather useless) usage of the `classMap` directive, to reproduce the module graph problem as explained above. While `pnpm dev` or `pnpm build && pnpm preview` kinda works (the app renders fine), you can still see in the `dist` output that the code for `classMap` is not shared but bundled AFAICT, as it is in the `/dist/assets/remote-app-Bcr1W7BH.js` chunk.

A "fun" way (actually took me hours of debugging) to illustrate the sharing problem is to run either the host with `pnpm dev` and the remote with `preview`, or vice versa. Lit has the interesting fact that it ships separate development and production builds in its [package exports](https://github.com/lit/lit/blob/main/packages/lit/package.json#L20-L23), and the two are not interoperable. In prod it does some [explicit deterministic terser-based mangling](https://github.com/lit/lit/blob/main/rollup-common.js#L91-L260) of method names. If both `lit` and `lit-html` are using the prod output, they still match and everything works. But you cannot mix them. If Lit is in dev mode and lit-html is prod, you will see a `TypeError: currentDirective._$initialize is not a function`, the other way around it'll be `TypeError: i._$AT is not a function`. This is reproducible on that branch, again with mixed `dev` vs. `preview` commands. Not the root cause of anything, just highlighting when sharing is not working. If both `lit` and `lit-html` would be equally shared, they both would be either in dev or prod mode, so no problem.

In the [second commit](https://github.com/gioboa/module-federation-vite-examples/pull/2/changes/6b3b82e16439fcaf4363019391d179d8fcc91cf2), I then tried to also explicitly share `lit-html` (had to add it as a dependency to allow the vite plugin to resolve it, otherwise pnpm wouldn't make it resolveable as a transitive dep). Still no success.

With both host and remote running in `dev`, I get `TypeError: html is not a function` (coming from `import { html } from 'lit'`). With mixed modes, I still get `i._$AT is not a function`. `classMap` is still bundled into remote-app.js.

Besides obviously hoping for a solution/fix, I wonder what the expectation for MF with such a case of transitive shared deps would be? Should it be enough to declare the direct dependency (`lit` here) as shared, and everything that it uses or re-exports should get bundled into the shared chunk and not need an explicitly shared config? Or are we expected to declare transitive deps (here `lit-html`, `lit-element`, maybe more?) explicitly as shared as well?

### Version

7.3.1

### Reproduction

https://github.com/gioboa/module-federation-vite-examples/pull/2

### Relevant log output

```shell

```

### Validations

- [x] Read the [docs](https://github.com/module-federation/vite).
- [x] Read the [common issues list](https://github.com/module-federation/vite/issues).
- [x] Check that there isn't [already an issue](https://github.com/module-federation/vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by gioboa**
Close #606 #607

### CODE REVIEW

File: src/plugins/pluginProxySharedModule_preBuild.ts [hunk 1]
```diff
@@ -22,6 +31,56 @@ function getPrebuildResolutionSource(pkgName: string, shareItem?: ShareItem): st
...
+      } catch {
+        // skip
+      }
+    }
+  }
+  return [];
+}
+
+/**
+ * In dev mode, detects shared packages that are sub-dependencies of other
```
Comment (gioboa) [inline src/plugins/pluginProxySharedModule_preBuild.ts:58]: @simonihmig after few different implementations and debugging sessions this solution looks the best one to avoid regressions and apply an automatic fix.

**Review by gioboa — COMMENTED** [review]
### Tests With Different Frameworks

Screenshot 2026-04-10 at 14 13 07
