### PR TITLE
fix: prevent race condition 🏎️  in parallel processes

### LINKED ISSUE #445: [Bug]: EEXIST crashes during parallel builds
### Describe the bug

My apologies, I cannot provide a minimal reproduction because this seems to occur with a rather large Nx project. In it, each application depends on `@module-federation/vite`.
However, I can explain what fixed the issue for us and what I suspect to be the culprit.

- This only seems to happen on CI environments, although both our CI and local environments work with 3 parallel processes
- This has happened sometime between 1.9.1 and 1.11.0. I suspect [this commit](https://github.com/module-federation/vite/commit/2ec3837b05bdd40cbf9d142ab3c1eb75d4e15c01#diff-f3b55e4d3853ba8a4e526608cd664bbef26ff09465db38905ec7d4a8dcdfd118R11) started it.

Disclaimer: I haven't looked into how the order of operation works, but I worked around the issue by changing `initVirtualModuleInfrastructure` to do

```js
try {
	mkdirSync(virtualPackagePath);
	writeFileSync(resolve(virtualPackagePath, "empty.js"), "");
	writeFileSync(resolve(virtualPackagePath, "package.json"), JSON.stringify({
		name: virtualModuleDir,
		main: "empty.js"
	}));
} catch(e) {
	if (e.code !== 'EEXIST') {
		throw e;
	}
}
```

This smells as incorrect but doesn't seem to break anything at a glance.

### Version

1.12.0

### Reproduction

-

### Relevant log output

```shell
[2026-03-06 09:11:14]  NX   Failed to process project graph.
[2026-03-06 09:11:14] 
[2026-03-06 09:11:14]      - apps/[REDACTED]/vite.config.ts: Error: EEXIST: file already exists, mkdir '/builds/[REDACTED]/frontend/node_modules/__mf__virtual'
[2026-03-06 09:11:14]       at mkdirSync (node:fs:1363:26)
[2026-03-06 09:11:14]       at VirtualModule.ensureVirtualPackageExists (file:///builds/[REDACTED]/frontend/node_modules/.pnpm/@module-federation+vite@1.12.0_rollup@4.57.1_typescript@5.9.3_vite@7.3.0_@types+node@22_aaa3d186ad005a7162071d933ce123a2/node_modules/@module-federation/vite/lib/index.mjs:814:4)
[2026-03-06 09:11:14]       at BasicMinimalPluginContext.configResolved (file:///builds/[REDACTED]/frontend/node_modules/.pnpm/@module-federation+vite@1.12.0_rollup@4.57.1_typescript@5.9.3_vite@7.3.0_@types+node@22_aaa3d186ad005a7162071d933ce123a2/node_modules/@module-federation/vite/lib/index.mjs:1970:19)
[2026-03-06 09:11:14]       at file:///builds/[REDACTED]/frontend/node_modules/.pnpm/vite@7.3.0_@types+node@22.13.0_jiti@2.6.1_lightningcss@1.29.2_sass@1.79.3_terser@5.46.0_tsx@4.19.2_yaml@2.8.0/node_modules/vite/dist/node/chunks/config.js:35673:87
[2026-03-06 09:11:14]       at Array.map (<anonymous>)
[2026-03-06 09:11:14]       at resolveConfig (file:///builds/[REDACTED]/frontend/node_modules/.pnpm/vite@7.3.0_@types+node@22.13.0_jiti@2.6.1_lightningcss@1.29.2_sass@1.79.3_terser@5.46.0_tsx@4.19.2_yaml@2.8.0/node_modules/vite/dist/node/chunks/config.js:35673:68)
[2026-03-06 09:11:14]       at buildVitestTargets (/builds/[REDACTED]/frontend/node_modules/.pnpm/@nx+vitest@22.4.1_@babel+traverse@7.29.0_@swc-node+register@1.10.9_@swc+core@1.15.11_@s_f818f5748b0afc593c3d995cc6f0e85c/node_modules/@nx/vitest/src/plugins/plugin.js:104:29)
[2026-03-06 09:11:14]       at /builds/[REDACTED]/frontend/node_modules/.pnpm/@nx+vitest@22.4.1_@babel+traverse@7.29.0_@swc-node+register@1.10.9_@swc+core@1.15.11_@s_f818f5748b0afc593c3d995cc6f0e85c/node_modules/@nx/vitest/src/plugins/plugin.js:60:21
[2026-03-06 09:11:14]       at /builds/[REDACTED]/frontend/node_modules/.pnpm/nx@22.4.1_@swc-node+register@1.10.9_@swc+core@1.15.11_@swc+types@0.1.17_typescript@5.9.3__@swc+core@1.15.11/node_modules/nx/src/project-graph/plugins/utils.js:10:27
[2026-03-06 09:11:14]       at async Promise.all (index 4)
[2026-03-06 09:11:14]       Error: EEXIST: file already exists, mkdir '/builds/[REDACTED]/frontend/node_modules/__mf__virtual'
[2026-03-06 09:11:14]           at mkdirSync (node:fs:1363:26)
[2026-03-06 09:11:14]           at VirtualModule.ensureVirtualPackageExists (file:///builds/[REDACTED]/frontend/node_modules/.pnpm/@module-federation+vite@1.12.0_rollup@4.57.1_typescript@5.9.3_vite@7.3.0_@types+node@22_aaa3d186ad005a7162071d933ce123a2/node_modules/@module-federation/vite/lib/index.mjs:814:4)
[2026-03-06 09:11:14]           at BasicMinimalPluginContext.configResolved (file:///builds/[REDACTED]/frontend/node_modules/.pnpm/@module-federation+vite@1.12.0_rollup@4.57.1_typescript@5.9.3_vite@7.3.0_@types+node@22_aaa3d186ad005a7162071d933ce123a2/node_modules/@module-federation/vite/lib/index.mjs:1970:19)
[2026-03-06 09:11:14]           at file:///builds/[REDACTED]/frontend/node_modules/.pnpm/vite@7.3.0_@types+node@22.13.0_jiti@2.6.1_lightningcss@1.29.2_sass@1.79.3_terser@5.46.0_tsx@4.19.2_yaml@2.8.0/node_modules/vite/dist/node/chunks/config.js:35673:87
[2026-03-06 09:11:14]           at Array.map (<anonymous>)
[2026-03-06 09:11:14]           at resolveConfig (file:///builds/[REDACTED]/frontend/node_modules/.pnpm/vite@7.3.0_@types+node@22.13.0_jiti@2.6.1_lightningcss@1.29.2_sass@1.79.3_terser@5.46.0_tsx@4.19.2_yaml@2.8.0/node_modules/vite/dist/node/chunks/config.js:35673:68)
[2026-03-06 09:11:14]           at buildVitestTargets (/builds/[REDACTED]/frontend/node_modules/.pnpm/@nx+vitest@22.4.1_@babel+traverse@7.29.0_@swc-node+register@1.10.9_@swc+core@1.15.11_@s_f818f5748b0afc593c3d995cc6f0e85c/node_modules/@nx/vitest/src/plugins/plugin.js:104:29)
[2026-03-06 09:11:14]           at /builds/[REDACTED]/frontend/node_modules/.pnpm/@nx+vitest@22.4.1_@babel+traverse@7.29.0_@swc-node+register@1.10.9_@swc+core@1.15.11_@s_f818f5748b0afc593c3d995cc6f0e85c/node_modules/@nx/vitest/src/plugins/plugin.js:60:21
[2026-03-06 09:11:14]           at /builds/[REDACTED]/frontend/node_modules/.pnpm/nx@22.4.1_@swc-node+register@1.10.9_@swc+core@1.15.11_@swc+types@0.1.17_typescript@5.9.3__@swc+core@1.15.11/node_modules/nx/src/project-graph/plugins/utils.js:10:27
[2026-03-06 09:11:14]           at async Promise.all (index 4)
```

### Validations

- [x] Read the [docs](https://github.com/module-federation/vite).
- [x] Read the [common issues list](https://github.com/module-federation/vite/issues).
- [x] Check that there isn't [already an issue](https://github.com/module-federation/vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by gioboa**
Close #445

### CODE REVIEW

File: src/utils/VirtualModule.ts [hunk 1]
```diff
@@ -113,17 +111,15 @@ export default class VirtualModule {
     const { virtualModuleDir } = getNormalizeModuleFederationOptions();
     const virtualPackagePath = resolve(nodeModulesDir, virtualModuleDir);
 
-    if (!existsSync(virtualPackagePath)) {
```
Comment (gioboa) [inline src/utils/VirtualModule.ts:116]: This was the issue in parallel executions. Both processes check at nearly the same time, both see the directory doesn't exist, both try to create it. The second one crashes because it already exists by then. cc @vergilfromadyen

Comment (vergilfromadyen) [reply src/utils/VirtualModule.ts:116]: @gioboa so `{ recursive: true }` on `mkdir` will address the race condition when creating the directory, but I believe `writeFileSync` is not atomic, so I think two parallel processes can mix bytes across writes, resulting in a corrupted file. I don't know what the chance of this is in practice, but [`npm` even has `write-file-atomic`](https://github.com/npm/write-file-atomic).

Should this write to an ephemeral location, then `renameSync` instead?

Comment (gioboa) [reply src/utils/VirtualModule.ts:116]: these files are tiny and both processes write the exact same content, so interleaved writes still produce the correct result. The real race condition (the existsSync + mkdirSync TOCTOU) is already fixed by removing the check and using { recursive: true }. Thanks for your thoughts.

Comment (VPenkov) [reply src/utils/VirtualModule.ts:116]: Thanks for double checking! I'll run some tests on Monday and keep you posted.
