### PR TITLE
fix: getting share item when package is only partially shared (fixes #288)

### LINKED ISSUE #288: [Bug]: Partial shared package
### Describe the bug

   We try to override a shared package partially (sub path). In our case it is
```
  shared: {
      react: {
        singleton: true,
      },
      'react-dom': {
        singleton: true,
      },
      '@eschbach/app-sdk/extensions/shared/v1': {
        singleton: true,
      },
      ...mfOptions.shared,
    },
```

The problem looks like it's here:

Image
It is removing the path of the provided package using removePathFromNpmPackage and cannot find the key anymore.

https://github.com/module-federation/core/issues/3682#issuecomment-2799878077

### Version

.

### Reproduction

Company internal code, I'm sorry.

### Relevant log output

```shell

```

### Validations

- [x] Read the [docs](https://github.com/module-federation/vite).
- [x] Read the [common issues list](https://github.com/module-federation/vite/issues).
- [x] Check that there isn't [already an issue](https://github.com/module-federation/vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by danieldaeschle**
Fixes #288 

@gioboa I hope this fix is good. I have no clue how it's supposed to work. I also did not test this change yet, but I think it should work logically wise.

### CODE REVIEW

**Comment by danieldaeschle** [comment]
I will try to provide something next week.

**Review by gioboa — COMMENTED** [review]
Thanks 💪

**Comment by danieldaeschle** [comment]
Sorry, didn't find time yet.

**Review by gioboa — COMMENTED** [review]
@danieldaeschle Thanks again for your help :rocket: 
I will be more than happy to merge it. Can you provide me a basic example to validate this fix please?

**Comment by gioboa** [comment]
> https://github.com/danieldaeschle/module-federation-vite-bug-partial-shared-package

Thanks for it. I'll check it out in soonish

File: src/utils/normalizeModuleFederationOptions.ts [hunk 1]
```diff
@@ -341,6 +341,7 @@ export function getNormalizeModuleFederationOptions() {
 export function getNormalizeShareItem(key: string) {
   const options = getNormalizeModuleFederationOptions();
   const shareItem =
+    options.shared[key] ||
```
Comment (gioboa) [inline src/utils/normalizeModuleFederationOptions.ts:344]: I tested the solution and It's working :clap: 
Thanks @danieldaeschle 
image
