### PR TITLE
fix: searchPackageVersion package.json resolution

### LINKED ISSUE #293: [Bug]: normalizeShareItem() fails to resolve package version
### Describe the bug

I'm a maintainer of https://github.com/connectrpc/connect-query-es/, and we've had a user report that our package can't be used as a shared package with federation: https://github.com/connectrpc/connect-query-es/pull/531

I see that https://github.com/module-federation/vite/pull/246 already added a fallback to resolve the package version in case `package.json` isn't exported. In case of `@connectrpc/connect-query`, `searchPackageVersion` is thrown off by another package.json file. 

The package structure is as follows:

```
.
├── README.md
├── dist
│   ├── cjs
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   ├── package.json
│   │   ├── ...
│   │   ├── use-transport.d.ts
│   │   └── use-transport.js
│   └── esm
│       ├── index.d.ts
│       ├── index.js
│       ├── ...
│       ├── use-transport.d.ts
│       └── use-transport.js
└── package.json
```

Because `searchPackageVersion` starts looking at `node_modules/@connectrpc/connect-query/dist/cjs/index.js`, it finds `node_modules/@connectrpc/connect-query/dist/cjs/package.json` first, and stops looking for `node_modules/@connectrpc/connect-query/package.json`.

We're using the same structure in many other packages, and I've seen the same pattern used elsewhere. (It's a workaround for dual packages that relies on the Node.js module resolution algorithm.)

### Version

@module-federation/vite@1.2.6

### Reproduction

https://github.com/Facegrinder/connect-query-microfrontend-bug-showcase

### Relevant log output

```shell
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /XXXconnect-query-microfrontend-bug-showcase/host/node_modules/@connectrpc/connect-query/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:634:36)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at normalizeShareItem (/connect-query-microfrontend-bug-showcase/host/node_modules/@module-federation/vite/lib/index.cjs:357:15)
    at /connect-query-microfrontend-bug-showcase/host/node_modules/@module-federation/vite/lib/index.cjs:397:21 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Validations

- [x] Read the [docs](https://github.com/module-federation/vite).
- [x] Read the [common issues list](https://github.com/module-federation/vite/issues).
- [x] Check that there isn't [already an issue](https://github.com/module-federation/vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by timostamm**
Fixes #293

### CODE REVIEW

File: src/utils/normalizeModuleFederationOptions.ts [hunk 1]
```diff
@@ -133,9 +133,17 @@ function searchPackageVersion(sharedName: string): string | undefined {
...
-        return require(potentialPackageJson).version;
+      const potentialPackageJsonPath = path.join(potentialPackageJsonDir, 'package.json');
+      if (fs.existsSync(potentialPackageJsonPath)) {
+        const potentialPackageJson = require(potentialPackageJsonPath);
+        if (
+          typeof potentialPackageJson == 'object' &&
+          potentialPackageJson !== null &&
+          typeof potentialPackageJson.version === 'string' &&
+          potentialPackageJson.name === sharedName
+        ) {
```
Comment (timostamm) [inline src/utils/normalizeModuleFederationOptions.ts:144]: Adding additional checks for the package.json candidate:
- is an object
- has a `version` property that's a string
- has a `name` property that matches what we're looking for

Only then do we return the version. Otherwise, we continue looking up the directory tree.

**Review by gioboa — COMMENTED** [review]
Thanks for your help @timostamm 
You can add your package [here](https://github.com/module-federation/vite/blob/7114b3896da362488f9d3ffcba0c2091d618c893/examples/vite-webpack-rspack/tests-remote/package.json#L15). This will test the change with our pipeline. :+1:

**Comment by timostamm** [comment]
> This will test the change with our pipeline.

Done in https://github.com/module-federation/vite/pull/294/commits/069db70a4d856d28c5da4e31bb76f4a928cf80f0 🤞

**Comment by gioboa** [comment]
> > This will test the change with our pipeline.
> 
> Done in [069db70](https://github.com/module-federation/vite/commit/069db70a4d856d28c5da4e31bb76f4a928cf80f0) 🤞

Yep, sorry. we need to use it as well, but don't worry I removed it.

File: src/utils/normalizeModuleFederationOptions.ts (hunk 1 above)
Comment (gioboa) [reply src/utils/normalizeModuleFederationOptions.ts:144]: Thanks for the explanation

**Review by gioboa — APPROVED** [review]
