### PR TITLE
fix: solve errors with mixing dev/prod React apps

### LINKED ISSUE #476: [Bug]: React 19 - Mixing dev/prod React builds breaks
### Describe the bug

Bug described perfectly here: https://github.com/module-federation/core/discussions/4103

### Version

7.3.1

### Reproduction

https://github.com/module-federation/core/discussions/4103

Same as previously reported issue: https://github.com/module-federation/vite/issues/297

Key is to create a production build and consume that in a local dev server.

### Validations

- [x] Read the [docs](https://github.com/module-federation/vite).
- [x] Read the [common issues list](https://github.com/module-federation/vite/issues).
- [x] Check that there isn't [already an issue](https://github.com/module-federation/vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by gioboa**
Close #476

### CODE REVIEW

File: src/virtualModules/virtualRemoteEntry.ts [hunk 1]
```diff
@@ -55,7 +53,7 @@ export function generateLocalSharedImportMap() {
           ${
             shareItem?.shareConfig.import === false
               ? `throw new Error(\`Shared module '\${${JSON.stringify(pkg)}}' must be provided by host\`);`
-              : isVinext && pkg === 'react'
+              : pkg === 'react'
```
Comment (wojtask9) [inline src/virtualModules/virtualRemoteEntry.ts]: out of curiosity. Why different `paths` for `react` ?

**Comment by wojtask9** [comment]
out of curiosity. Why different paths for react ?

File: src/index.ts [hunk 2]
```diff
@@ -50,6 +50,27 @@ import {
...
+  '\f': '\\f',
+  '\n': '\\n',
+  '\r': '\\r',
+  '\t': '\\t',
+  '\0': '\\0',
+  '\u2028': '\\u2028',
+  '\u2029': '\\u2029',
+};
+
+function escapeUnsafeJsSourceChars(str: string): string {
```
Comment (devinrhode2) [inline src/index.ts:68]: Just started to read code.. still piecing things together... react 19 src must have some of these chars?

Comment (devinrhode2) [reply src/index.ts:68]: Seems like a code comment would go a long ways here

File: examples/vite-vite/vite-remote/package.json [hunk 3]
```diff
@@ -5,7 +5,9 @@
   "scripts": {
     "dev": "vite",
     "build": "vite build",
-    "preview": "vite build && vite preview"
+    "preview": "vite build && vite preview",
+    "mixed:1": "vite build && vite preview",
+    "mixed:2": "MIXED_VV=2 NODE_ENV=production vite"
```
Comment (gioboa) [inline examples/vite-vite/vite-remote/package.json:10]: We need to set production to serve the correct bundle.

File: src/index.ts (hunk 2 above)
Comment (devinrhode2) [reply src/index.ts:68]: Cleaning up old browser tabs... curious what this change was about
